version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  setup:
    docker:
      - image: circleci/node:10.12
    working_directory: ~/checkout
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "src/package-lock.json"}}
            - npm-deps-{{ .Branch }}
            - npm-deps-
      - run:
          name: install
          command: npm install
          working_directory: src
      - save_cache:
          key: npm-deps-{{ .Branch }}-{{ checksum "src/package-lock.json"}}
          paths:
            - src/node_modules
      - run:
          name: test
          command: npm test
          working_directory: src
  deploy:
    executor: aws-cli/default
    working_directory: ~/checkout
    steps:
      - checkout
      - aws-cli/install
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "src/package-lock.json"}}
            - npm-deps-{{ .Branch }}
            - npm-deps-
      - deploy: 
          command: | 
            aws cloudformation package --s3-bucket my-lambda-function-deployment --template-file template.yml --output-template-file packaged-template.yml
            aws cloudformation deploy --template-file packaged-template.yml --stack-name=ThrowTrashSkill --parameter-overrides APPID=${APPID}
          working_directory: deploy

workflows:
  all_build:
    jobs:
      - setup:
          context: aws-test
      - deploy:
          context: aws-deploy
          requires:
            - setup

