version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  setup:
    docker:
      - image: circleci/node:10.12
    working_directory: ~/checkout
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "src/package-lock.json"}}
            - npm-deps-{{ .Branch }}
            - npm-deps-
      - run:
          name: install
          command: npm install
          working_directory: src
      - save_cache:
          key: npm-deps-{{ .Branch }}-{{ checksum "src/package-lock.json"}}
          paths:
            - src/node_modules
      - run:
          name: test
          command: |
            mkdir -p ~/.ask
            echo "${ASK_CLI_CONFIG}" > ~/.ask/cli_config
            echo `ask api get-model -s ${APPID} --stage development -l ja-JP` | jq '.' > test/model.json
            npm test
          working_directory: src
  deploy:
    executor: aws-cli/default
    working_directory: ~/checkout
    steps:
      - checkout
      - aws-cli/install
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "src/package-lock.json"}}
            - npm-deps-{{ .Branch }}
            - npm-deps-
      - deploy: 
          command: | 
            if [ "${CIRCLE_BRANCH}" == "master"]; then
              STAGE = "PRODUCTION"
              MecabApi_URL = ${MecabAPI_URL_PRODUCTION}
            else
              STAGE = "TEST"
              MecabApi_URL = ${MecabAPI_URL_TEST}
            fi
            aws cloudformation package --s3-bucket my-lambda-function-deployment --template-file template.yml --output-template-file packaged-template.yml
            aws cloudformation deploy --template-file packaged-template.yml --stack-name=ThrowTrashSkill --parameter-overrides APPID=${APPID} STAGE=${STAGE} MecabAPI_URL=${MecabAPI_URL} --role-arn ${CloudFOrmationRole}
          working_directory: deploy

workflows:
  all_build:
    jobs:
      - setup:
          context: aws-test
      - deploy:
          context: aws-deploy
          requires:
            - setup

