AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for BSE Workflow
Parameters:
  APPID:
    Type: "String"
  STAGE:
    Type: "String"
    Default: "PRODUCTION"
  APIURL:
    Type: "String"
  REMINDERPRODUCTID:
    Type: "String"
Resources:
  LambdaExecPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "dynamodb:*"
            Resource: 
              - !GetAtt TrashScheduleTable.Arn
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/throwtrash-backend-accesstoken"
          -
            Effect: "Allow"
            Action: "lambda:*"
            Resource: 
              - !GetAtt ThrowTrashSkill.Arn
          -
            Effect: "Allow"
            Action: 
               - "s3:ListBucket"
               - "s3:GetObject"
               - "s3:PutObject"
            Resource: 
              - !GetAtt HistoryBucket.Arn
              - !Sub 
                - "${HistoryBucket}/*"
                - {HistoryBucket: !GetAtt HistoryBucket.Arn}

      PolicyName: !Sub "throwtrash-lambda-policy-${AWS::Region}"
      Roles:
        - !Ref LambdaExecRole
    DeletionPolicy: Retain
  LambdaExecRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      RoleName: !Sub "throwtrash-lambda-role-${AWS::Region}"
    DeletionPolicy: Retain
  HistoryBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "throwtrash-user-history-${AWS::Region}"
    DeletionPolicy: Retain
  TrashScheduleTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "signinId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        -
          IndexName: "signinId-index"
          KeySchema:
            - 
              AttributeName: "signinId"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "description"
              - "id"
              - "signinService"
            ProjectionType: "INCLUDE"
      StreamSpecification:
        StreamViewType: "NEW_IMAGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: "TrashSchedule"
    DeletionPolicy: Retain
  ThrowTrashSkill:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ../src
      FunctionName: ThrowTrashSkill
      Handler: index.handler
      Role: !GetAtt LambdaExecRole.Arn
      Runtime: nodejs10.x
      Timeout: 30
      Environment:
        Variables:
          APP_REGION: !Sub "${AWS::Region}"
          APP_ID: !Ref APPID
          STAGE: !Ref STAGE
          MecabAPI_URL: !Ref APIURL
          REMINDER_PRODUCT_ID: !Ref REMINDERPRODUCTID
    DeletionPolicy: Retain
  LambdaEvent:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref ThrowTrashSkill
      Principal: "alexa-appkit.amazon.com"
      EventSourceToken: !Ref APPID