AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for BSE Workflow
Parameters:
  APPID:
    Type: "String"
  STAGE:
    Type: "String"
    Default: "PRODUCTION"
Resources:
  LambdaExecPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "dynamodb:*"
            Resource: 
              - !GetAtt HistoryTable.Arn
              - !GetAtt TrashScheduleTable.Arn
          -
            Effect: "Allow"
            Action: "lambda:*"
            Resource: 
              - !GetAtt ThrowTrashSkill.Arn
      PolicyName: !Sub "throwtrash-lambda-policy-${AWS::Region}"
      Roles:
        - !Ref LambdaExecRole
    DeletionPolicy: Retain
  LambdaExecRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      RoleName: !Sub "throwtrash-lambda-role-${AWS::Region}"
    DeletionPolicy: Retain
  HistoryTable:
    Type: "AWS::Serverless::SimpleTable"
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: ThrowTrashHistory
    DeletionPolicy: Retain
  TrashScheduleTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "signinId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        -
          IndexName: "signinId-index"
          KeySchema:
            - 
              AttributeName: "signinId"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "description"
              - "id"
              - "signinService"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: "NEW_IMAGE"
      TableName: "TrashSchedule"
  ThrowTrashSkill:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ../src
      FunctionName: ThrowTrashSkill
      Handler: index.handler
      Role: !GetAtt LambdaExecRole.Arn
      Runtime: nodejs10.x
      Timeout: 30
      Environment:
        Variables:
          APP_REGION: !Sub "${AWS::Region}"
          APP_ID: !Ref APPID
          STAGE: !Ref STAGE
    DeletionPolicy: Retain
  LambdaEvent:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref ThrowTrashSkill
      Principal: "alexa-appkit.amazon.com"
      EventSourceToken: !Ref APPID