version: "3"
services: 
  node:
    build: .
    volumes:
      - ../:/workspace
      - /workspace/app/node_modules
      - /workspace/batch/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"